apiVersion: 1

deleteDatasources:
  - name: PostgreSQL - dashed
    orgId: 1

datasources:
  - name: PostgreSQL - dashed
    orgId: 1
    type: postgres
    typeName: PostgreSQL
    typeLogoUrl: public/app/plugins/datasource/postgres/img/postgresql_logo.svg
    access: proxy
    url: postgres:5432
    user: "$POSTGRES_USER"
    database: dashed
    secureJsonData:
      password: "$POSTGRES_PASSWORD"
    jsonData:
      postgresVersion: 1500
      sslmode: disable
    readOnly: false
    isDefault: true
