version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=dashed"
    ports:
      - '5432:5432'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana-oss
    restart: always
    environment:
      - "GF_SECURITY_ADMIN_USER=${GRAFANA_USER}"
      - "GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards

volumes:
  postgres-volume:
    driver: local
  grafana-storage:
    driver: local
